from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Place


AREA_COORDS = {
    "Banjara Hills": (17.4156, 78.4372, 38, 48),
    "Jubilee Hills": (17.4326, 78.4090, 22, 32),
    "Madhapur": (17.4483, 78.3915, 74, 44),
    "Hitech City": (17.4474, 78.3784, 64, 60),
    "Gachibowli": (17.4401, 78.3489, 82, 52),
    "Kondapur": (17.4697, 78.3578, 79, 38),
    "Kukatpally": (17.4948, 78.3996, 62, 18),
    "Ameerpet": (17.4375, 78.4483, 28, 62),
    "Secunderabad": (17.4435, 78.4983, 57, 26),
    "Old City": (17.3616, 78.4747, 10, 78),
    "Begumpet": (17.4447, 78.4664, 45, 37),
    "Abids": (17.3898, 78.4766, 31, 74),
    "Koti": (17.3850, 78.4867, 36, 72),
    "Dilsukhnagar": (17.3688, 78.5247, 54, 80),
    "Manikonda": (17.4000, 78.3762, 76, 64),
    "Nallagandla": (17.4752, 78.3091, 91, 42),
    "Tolichowki": (17.3984, 78.4110, 21, 61),
    "Mehdipatnam": (17.3940, 78.4427, 24, 70),
    "Sainikpuri": (17.4986, 78.5527, 72, 13),
    "Kompally": (17.5385, 78.4814, 49, 9),
}

CATEGORY_PROFILES = {
    "biryani": {
        "emoji": "🍛",
        "restaurant_type": "family place",
        "cuisines": ["Hyderabadi", "Biryani"],
        "tags": ["biryani", "dum", "spicy", "family-friendly"],
        "occasions": ["biryani-run", "team-lunch", "family-dinner"],
        "names": [
            "Paradise",
            "Shah Ghouse",
            "Bawarchi",
            "Meridian",
            "Cafe Bahar",
            "Pista House",
            "Grand Hotel",
            "Nayaab",
            "Mehfil",
            "Hotel Shadab",
            "Spice Junction",
            "Dum Darbar",
            "Deccan Biryani House",
            "Nizam's Kitchen",
            "Charcoal Biryani Co",
            "Royal Dum House",
            "Hyderabadi Handi",
        ],
    },
    "tiffin": {
        "emoji": "🥘",
        "restaurant_type": "tiffins",
        "cuisines": ["South Indian", "Breakfast"],
        "tags": ["dosa", "idli", "breakfast", "value"],
        "occasions": ["breakfast", "budget", "team-lunch"],
        "names": [
            "Chutneys",
            "Minerva Coffee Shop",
            "Ram Ki Bandi",
            "Taaza Kitchen",
            "Pragati Tiffins",
            "Govind Dosa",
            "Udupi Upahar",
            "Varalakshmi Tiffins",
            "Dosa Factory",
            "Morning Plate",
            "Ghee Karam Tiffins",
            "Tiffin Theory",
            "Andhra Tiffin Room",
            "Steam & Sambar",
            "Idli Street",
            "Pesarattu Point",
            "South Spoon",
        ],
    },
    "cafe": {
        "emoji": "☕",
        "restaurant_type": "cafe",
        "cuisines": ["Cafe", "Bakery"],
        "tags": ["coffee", "dessert", "wifi", "casual"],
        "occasions": ["date", "work-from-cafe", "chai-break"],
        "names": [
            "Nimrah Cafe",
            "Roastery Coffee House",
            "Autumn Leaf Cafe",
            "Concu",
            "The Hole In The Wall",
            "Cafe Niloufer",
            "Third Wave Coffee",
            "Ministry of Chai",
            "Cream Stone",
            "Labonel",
            "Coffee Cup",
            "Karafa Cafe",
            "Chai Kahani",
            "Brew Room",
            "Makers of Milkshakes",
            "Cafe Eclat",
            "Little Things Cafe",
        ],
    },
    "rooftop": {
        "emoji": "🌃",
        "restaurant_type": "restro bar",
        "cuisines": ["Modern Indian", "Continental", "Cocktails"],
        "tags": ["rooftop", "views", "cocktails", "upscale"],
        "occasions": ["date", "rooftop", "party"],
        "names": [
            "Farzi Cafe",
            "Over The Moon",
            "Aqua",
            "Air Live",
            "Altitude Lounge",
            "Broadway",
            "Skyhy",
            "Olive Bistro",
            "Rooftop Republic",
            "Cloud Dining",
            "Terrace Tales",
            "High Street Social",
            "Skyline Kitchen",
            "Moon Deck",
            "The Glasshouse",
            "Aura Terrace",
            "City Lights Bar",
        ],
    },
    "pub": {
        "emoji": "🍺",
        "restaurant_type": "pub",
        "cuisines": ["Pub food", "Continental"],
        "tags": ["pub", "music", "cocktails", "after work"],
        "occasions": ["party", "after-work", "team-lunch"],
        "names": [
            "10 Downing St",
            "Prost",
            "Heart Cup Coffee",
            "Zero40 Brewing",
            "Broadway Brewery",
            "By The Bottle",
            "Fat Pigeon",
            "Lord of the Drinks",
            "The Hoppery",
            "Prism Club",
            "Bar Project",
            "Tap House",
            "Mugshot Lounge",
            "Social Brew",
            "Nightjar",
            "The Local Bar",
            "Hop Street",
        ],
    },
    "street": {
        "emoji": "🌮",
        "restaurant_type": "street food",
        "cuisines": ["Street food", "Snacks"],
        "tags": ["chaat", "budget", "quick bite", "local"],
        "occasions": ["budget", "old-city-walk", "late-night"],
        "names": [
            "Gokul Chat",
            "Maharaja Chat",
            "Sindhi Colony Momos",
            "DLF Street Eats",
            "Charminar Kebab Lane",
            "Mayur Pan House",
            "Sardarji's Chaat",
            "Tibbs Frankie",
            "Bombay Juice",
            "Pani Puri Point",
            "Kebab Cart",
            "Rolls Junction",
            "Chaat Bazaar",
            "Evening Adda",
            "Old City Snacks",
            "Momo Street",
            "Grill Cart",
        ],
    },
}

FEATURED_PLACES = [
    {
        "name": "Paradise",
        "area": "Secunderabad",
        "category": "biryani",
        "restaurant_type": "family place",
        "cuisines": ["Hyderabadi", "Biryani"],
        "tags": ["dum biryani", "iconic", "must-try", "Open now", "Legend"],
        "occasions": ["family-dinner", "team-lunch", "biryani-run"],
        "emoji": "🍛",
        "latitude": 17.4435,
        "longitude": 78.4983,
        "map_x": 57,
        "map_y": 26,
        "rating": 4.9,
        "reviews_count": 8900,
        "score": 9.4,
        "food_score": 4.9,
        "ambience_score": 3.8,
        "service_score": 4.5,
        "value_score": 4.8,
        "wait_score": 3.2,
        "ai_summary": "People swear by the dum biryani. Ambience is old-school and functional. Long queues on weekends but usually worth it.",
    },
    {
        "name": "Nimrah Cafe",
        "area": "Old City",
        "category": "cafe",
        "restaurant_type": "irani cafe",
        "cuisines": ["Irani chai", "Bakery"],
        "tags": ["irani chai", "osmania biscuits", "iconic", "Open till late"],
        "occasions": ["old-city-walk", "chai-break", "budget"],
        "emoji": "☕",
        "latitude": 17.3616,
        "longitude": 78.4747,
        "map_x": 10,
        "map_y": 78,
        "rating": 4.7,
        "reviews_count": 3200,
        "score": 8.9,
        "food_score": 4.7,
        "ambience_score": 4.2,
        "service_score": 4.1,
        "value_score": 4.9,
        "wait_score": 3.8,
        "ai_summary": "The classic Irani chai experience near Charminar. Osmania biscuits are mandatory and late-night crowds are part of the charm.",
    },
    {
        "name": "Farzi Cafe",
        "area": "Banjara Hills",
        "category": "rooftop",
        "restaurant_type": "restro bar",
        "cuisines": ["Modern Indian", "Cocktails"],
        "tags": ["rooftop", "molecular", "cocktails", "upscale"],
        "occasions": ["date", "rooftop", "party"],
        "emoji": "🌃",
        "latitude": 17.4156,
        "longitude": 78.4372,
        "map_x": 38,
        "map_y": 48,
        "rating": 4.5,
        "reviews_count": 2100,
        "score": 8.7,
        "food_score": 4.4,
        "ambience_score": 4.8,
        "service_score": 4.3,
        "value_score": 3.9,
        "wait_score": 4.0,
        "ai_summary": "A polished date-night option with city views, theatrical plates, and strong cocktails. Book ahead on weekends.",
    },
    {
        "name": "Chutneys",
        "area": "Jubilee Hills",
        "category": "tiffin",
        "restaurant_type": "tiffins",
        "cuisines": ["South Indian", "Breakfast"],
        "tags": ["dosas", "tiffin", "breakfast", "family-friendly", "Open early"],
        "occasions": ["breakfast", "family-dinner", "team-lunch"],
        "emoji": "🥘",
        "latitude": 17.4326,
        "longitude": 78.4090,
        "map_x": 22,
        "map_y": 32,
        "rating": 4.8,
        "reviews_count": 5400,
        "score": 9.1,
        "food_score": 4.8,
        "ambience_score": 4.0,
        "service_score": 4.4,
        "value_score": 4.7,
        "wait_score": 3.5,
        "ai_summary": "A dependable South Indian breakfast pick. Go early if you want shorter waits and fresher dosa energy.",
    },
    {
        "name": "10 Downing St",
        "area": "Hitech City",
        "category": "pub",
        "restaurant_type": "pub",
        "cuisines": ["Pub food", "Continental"],
        "tags": ["pub", "live music", "cocktails", "after work"],
        "occasions": ["party", "team-lunch", "after-work"],
        "emoji": "🍺",
        "latitude": 17.4474,
        "longitude": 78.3784,
        "map_x": 64,
        "map_y": 60,
        "rating": 4.3,
        "reviews_count": 1800,
        "score": 8.2,
        "food_score": 4.1,
        "ambience_score": 4.6,
        "service_score": 4.2,
        "value_score": 3.8,
        "wait_score": 4.1,
        "ai_summary": "A reliable after-work pub for Hitech City. Best when the group wants music, snacks, and easy drinks.",
    },
    {
        "name": "Shah Ghouse",
        "area": "Old City",
        "category": "biryani",
        "restaurant_type": "quick service",
        "cuisines": ["Hyderabadi", "Biryani", "Haleem"],
        "tags": ["biryani", "haleem", "budget", "no-frills"],
        "occasions": ["biryani-run", "budget", "old-city-walk"],
        "emoji": "🍛",
        "latitude": 17.3578,
        "longitude": 78.4740,
        "map_x": 8,
        "map_y": 65,
        "rating": 4.6,
        "reviews_count": 6700,
        "score": 9.0,
        "food_score": 4.8,
        "ambience_score": 3.2,
        "service_score": 3.9,
        "value_score": 4.9,
        "wait_score": 3.0,
        "ai_summary": "No-frills biryani with serious local loyalty. Great value, busy counters, and excellent haleem in season.",
    },
]

CURATED_RESTAURANT_PLACES = [
    {
        "name": "Jewel of Nizam",
        "area": "Tolichowki",
        "category": "biryani",
        "restaurant_type": "fine dining",
        "cuisines": ["Hyderabadi", "Mughlai", "Biryani"],
        "tags": ["EatMap Best", "Rank #1", "fine dining", "royal dining", "Cost: Rs 3,000 for two", "Hours: Lunch and dinner", "Distance: 7.8 km"],
        "occasions": ["date", "family-dinner", "biryani-run"],
        "emoji": "🍛",
        "latitude": 17.3929,
        "longitude": 78.4037,
        "map_x": 19,
        "map_y": 63,
        "rating": 4.9,
        "reviews_count": 12300,
        "score": 9.8,
        "food_score": 4.9,
        "ambience_score": 4.9,
        "service_score": 4.8,
        "value_score": 4.2,
        "wait_score": 3.4,
        "ai_summary": "A splurge-worthy Hyderabadi dining room for biryani, kebabs, and family celebrations. Pick this when the meal needs to feel ceremonial.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-1",
    },
    {
        "name": "KOKO",
        "area": "Kondapur",
        "category": "pub",
        "restaurant_type": "resto bar",
        "cuisines": ["Asian", "Japanese", "Cocktails"],
        "tags": ["EatMap Best", "Rank #2", "pan asian", "cocktails", "Cost: Rs 2,500 for two", "Hours: Lunch to late night", "Distance: 12.4 km"],
        "occasions": ["date", "party", "after-work"],
        "emoji": "🍸",
        "latitude": 17.4599,
        "longitude": 78.3669,
        "map_x": 77,
        "map_y": 39,
        "rating": 4.9,
        "reviews_count": 9800,
        "score": 9.7,
        "food_score": 4.8,
        "ambience_score": 4.9,
        "service_score": 4.7,
        "value_score": 4.1,
        "wait_score": 3.7,
        "ai_summary": "A high-energy Pan-Asian pick with polished cocktails and strong date-night energy. Reserve ahead if you want a smooth weekend visit.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-2",
    },
    {
        "name": "Exotica",
        "area": "Banjara Hills",
        "category": "rooftop",
        "restaurant_type": "rooftop restaurant",
        "cuisines": ["North Indian", "Mughlai", "Continental"],
        "tags": ["EatMap Best", "Rank #3", "rooftop", "group friendly", "Cost: Rs 2,000 for two", "Hours: Lunch and dinner", "Distance: 4.9 km"],
        "occasions": ["rooftop", "family-dinner", "team-lunch"],
        "emoji": "🌃",
        "latitude": 17.4148,
        "longitude": 78.4382,
        "map_x": 38,
        "map_y": 48,
        "rating": 4.9,
        "reviews_count": 14100,
        "score": 9.6,
        "food_score": 4.7,
        "ambience_score": 4.9,
        "service_score": 4.6,
        "value_score": 4.3,
        "wait_score": 3.5,
        "ai_summary": "Reliable rooftop dining for large groups, North Indian mains, and a relaxed Banjara Hills evening. It is the safe upscale crowd-pleaser.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-3",
    },
    {
        "name": "Olive Bistro",
        "area": "Gachibowli",
        "category": "rooftop",
        "restaurant_type": "bistro",
        "cuisines": ["Mediterranean", "Italian", "European"],
        "tags": ["EatMap Best", "Rank #4", "romantic", "outdoor seating", "Cost: Rs 2,200 for two", "Hours: Lunch and dinner", "Distance: 13.1 km"],
        "occasions": ["date", "rooftop", "birthday"],
        "emoji": "🍝",
        "latitude": 17.4343,
        "longitude": 78.3389,
        "map_x": 84,
        "map_y": 54,
        "rating": 4.8,
        "reviews_count": 8600,
        "score": 9.5,
        "food_score": 4.6,
        "ambience_score": 4.9,
        "service_score": 4.6,
        "value_score": 4.0,
        "wait_score": 3.6,
        "ai_summary": "A pretty, leisurely bistro for date nights and birthday dinners. Go for the setting first, then stay for Mediterranean plates.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-4",
    },
    {
        "name": "The Fisherman's Wharf",
        "area": "Gachibowli",
        "category": "pub",
        "restaurant_type": "casual dining",
        "cuisines": ["Seafood", "Goan", "Continental"],
        "tags": ["EatMap Best", "Rank #5", "seafood", "live music", "Cost: Rs 2,000 for two", "Hours: Lunch to late night", "Distance: 12.9 km"],
        "occasions": ["party", "team-lunch", "family-dinner"],
        "emoji": "🍤",
        "latitude": 17.4388,
        "longitude": 78.3504,
        "map_x": 82,
        "map_y": 52,
        "rating": 4.8,
        "reviews_count": 10400,
        "score": 9.4,
        "food_score": 4.7,
        "ambience_score": 4.7,
        "service_score": 4.5,
        "value_score": 4.2,
        "wait_score": 3.8,
        "ai_summary": "A group-friendly seafood and Goan food pick with upbeat ambience. Best for office groups that want more than the usual buffet.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-5",
    },
    {
        "name": "Roastery Coffee House",
        "area": "Banjara Hills",
        "category": "cafe",
        "restaurant_type": "cafe",
        "cuisines": ["Cafe", "Coffee", "Desserts"],
        "tags": ["EatMap Best", "Rank #6", "specialty coffee", "work friendly", "Cost: Rs 900 for two", "Hours: Breakfast to late evening", "Distance: 4.6 km"],
        "occasions": ["work-from-cafe", "date", "chai-break"],
        "emoji": "☕",
        "latitude": 17.4153,
        "longitude": 78.4378,
        "map_x": 39,
        "map_y": 49,
        "rating": 4.8,
        "reviews_count": 9300,
        "score": 9.3,
        "food_score": 4.6,
        "ambience_score": 4.8,
        "service_score": 4.5,
        "value_score": 4.3,
        "wait_score": 3.9,
        "ai_summary": "A dependable coffee-first cafe for slow mornings, remote work, and casual dates. Expect a wait during peak coffee hours.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-6",
    },
    {
        "name": "Concu",
        "area": "Jubilee Hills",
        "category": "cafe",
        "restaurant_type": "dessert cafe",
        "cuisines": ["Desserts", "Cafe", "European"],
        "tags": ["EatMap Best", "Rank #7", "desserts", "date spot", "Cost: Rs 1,200 for two", "Hours: All day", "Distance: 5.7 km"],
        "occasions": ["date", "birthday", "work-from-cafe"],
        "emoji": "🍰",
        "latitude": 17.4308,
        "longitude": 78.4075,
        "map_x": 23,
        "map_y": 33,
        "rating": 4.8,
        "reviews_count": 7600,
        "score": 9.2,
        "food_score": 4.7,
        "ambience_score": 4.7,
        "service_score": 4.5,
        "value_score": 4.1,
        "wait_score": 4.0,
        "ai_summary": "A polished dessert cafe for celebration cakes, coffee, and quiet catch-ups. Strong pick when ambience matters as much as the plate.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-7",
    },
    {
        "name": "Burma Burma",
        "area": "Hitech City",
        "category": "tiffin",
        "restaurant_type": "casual dining",
        "cuisines": ["Burmese", "Asian", "Vegetarian"],
        "tags": ["EatMap Best", "Rank #8", "vegetarian", "tea room", "Cost: Rs 1,800 for two", "Hours: Lunch and dinner", "Distance: 11.2 km"],
        "occasions": ["team-lunch", "date", "family-dinner"],
        "emoji": "🥗",
        "latitude": 17.4449,
        "longitude": 78.3778,
        "map_x": 65,
        "map_y": 59,
        "rating": 4.8,
        "reviews_count": 6900,
        "score": 9.1,
        "food_score": 4.8,
        "ambience_score": 4.6,
        "service_score": 4.5,
        "value_score": 4.1,
        "wait_score": 3.9,
        "ai_summary": "A vegetarian Asian restaurant that feels special without becoming too formal. Great for teams with mixed food preferences.",
        "external_provider": "zomato",
        "external_id": "zomato-best-hyd-8",
    },
]

CURATED_NIGHTLIFE_PLACES = [
    {
        "name": "Exotica - Madhapur",
        "area": "Madhapur",
        "category": "rooftop",
        "restaurant_type": "rooftop restaurant",
        "cuisines": ["North Indian", "Chinese", "Continental"],
        "tags": ["EatMap Nightlife", "Rank #1", "rooftop", "group friendly", "Collection: Drinks & Nightlife", "Cost: Rs 2,000 for two", "Hours: Lunch to late night", "Distance: 9.7 km"],
        "occasions": ["party", "rooftop", "after-work"],
        "emoji": "🌃",
        "latitude": 17.4483,
        "longitude": 78.3915,
        "map_x": 73,
        "map_y": 45,
        "rating": 4.9,
        "reviews_count": 12800,
        "score": 9.6,
        "food_score": 4.7,
        "ambience_score": 4.9,
        "service_score": 4.6,
        "value_score": 4.2,
        "wait_score": 3.6,
        "ai_summary": "A polished rooftop pick for groups who want North Indian comfort food, drinks, and a breezy Madhapur evening.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-1",
    },
    {
        "name": "Qosa Kitchen & Bar",
        "area": "Banjara Hills",
        "category": "pub",
        "restaurant_type": "kitchen and bar",
        "cuisines": ["North Indian", "Asian", "Italian"],
        "tags": ["EatMap Nightlife", "Rank #2", "cocktails", "date night", "Collection: Drinks & Nightlife", "Cost: Rs 2,500 for two", "Hours: Lunch to late night", "Distance: 4.8 km"],
        "occasions": ["date", "party", "after-work"],
        "emoji": "🍸",
        "latitude": 17.4164,
        "longitude": 78.4371,
        "map_x": 40,
        "map_y": 49,
        "rating": 4.9,
        "reviews_count": 6400,
        "score": 9.5,
        "food_score": 4.7,
        "ambience_score": 4.8,
        "service_score": 4.6,
        "value_score": 4.1,
        "wait_score": 3.7,
        "ai_summary": "A stylish bar-forward dinner spot for cocktails, Asian plates, and a dressed-up Banjara Hills night.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-2",
    },
    {
        "name": "TG's - The Oriental Grill",
        "area": "Gachibowli",
        "category": "pub",
        "restaurant_type": "fine dining bar",
        "cuisines": ["Asian", "Japanese", "Sushi"],
        "tags": ["EatMap Nightlife", "Rank #3", "asian grill", "upscale", "Collection: Drinks & Nightlife", "Cost: Rs 4,000 for two", "Hours: Dinner", "Distance: 13.0 km"],
        "occasions": ["date", "party", "pub-night"],
        "emoji": "🍣",
        "latitude": 17.4379,
        "longitude": 78.3498,
        "map_x": 83,
        "map_y": 52,
        "rating": 4.9,
        "reviews_count": 5200,
        "score": 9.4,
        "food_score": 4.8,
        "ambience_score": 4.6,
        "service_score": 4.8,
        "value_score": 3.9,
        "wait_score": 3.8,
        "ai_summary": "An upscale Asian grill for sushi, robata-style plates, and a quieter premium drinks plan in Gachibowli.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-3",
    },
    {
        "name": "Kyma",
        "area": "Financial District",
        "category": "pub",
        "restaurant_type": "lounge bar",
        "cuisines": ["Mediterranean", "Asian", "Italian"],
        "tags": ["EatMap Nightlife", "Rank #4", "mediterranean", "cocktails", "Collection: Drinks & Nightlife", "Cost: Rs 2,500 for two", "Hours: Lunch to late night", "Distance: 14.2 km"],
        "occasions": ["party", "team-lunch", "after-work"],
        "emoji": "🍷",
        "latitude": 17.4242,
        "longitude": 78.3368,
        "map_x": 87,
        "map_y": 50,
        "rating": 4.8,
        "reviews_count": 9100,
        "score": 9.3,
        "food_score": 4.6,
        "ambience_score": 4.8,
        "service_score": 4.5,
        "value_score": 4.0,
        "wait_score": 3.8,
        "ai_summary": "A lively Mediterranean-leaning bar for big tables, cocktails, and late dinners around the Financial District.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-4",
    },
    {
        "name": "Margarita Deck",
        "area": "Hitech City",
        "category": "pub",
        "restaurant_type": "bar",
        "cuisines": ["Mexican", "Tex-Mex", "Bar Food"],
        "tags": ["EatMap Nightlife", "Rank #5", "mexican", "after work", "Collection: Drinks & Nightlife", "Cost: Rs 2,200 for two", "Hours: Lunch to late night", "Distance: 11.0 km"],
        "occasions": ["party", "after-work", "pub-night"],
        "emoji": "🍹",
        "latitude": 17.4469,
        "longitude": 78.3793,
        "map_x": 65,
        "map_y": 60,
        "rating": 4.8,
        "reviews_count": 7400,
        "score": 9.2,
        "food_score": 4.5,
        "ambience_score": 4.7,
        "service_score": 4.4,
        "value_score": 4.2,
        "wait_score": 3.7,
        "ai_summary": "A cheerful margarita-and-tacos plan for after-work groups that want drinks without going too formal.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-5",
    },
    {
        "name": "Kanak",
        "area": "Financial District",
        "category": "pub",
        "restaurant_type": "premium bar",
        "cuisines": ["North Indian", "Mughlai", "Cocktails"],
        "tags": ["EatMap Nightlife", "Rank #6", "north indian", "premium", "Collection: Drinks & Nightlife", "Cost: Rs 3,000 for two", "Hours: Lunch and dinner", "Distance: 14.4 km"],
        "occasions": ["date", "family-dinner", "pub-night"],
        "emoji": "🥃",
        "latitude": 17.4236,
        "longitude": 78.3375,
        "map_x": 88,
        "map_y": 49,
        "rating": 4.8,
        "reviews_count": 6100,
        "score": 9.1,
        "food_score": 4.7,
        "ambience_score": 4.7,
        "service_score": 4.6,
        "value_score": 4.0,
        "wait_score": 3.7,
        "ai_summary": "A premium North Indian dinner-and-drinks option when the group wants rich food, polished service, and a calmer setting.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-6",
    },
    {
        "name": "Hodd's Cocktail Bar - Hyatt Hyderabad Gachibowli",
        "area": "Gachibowli",
        "category": "pub",
        "restaurant_type": "cocktail bar",
        "cuisines": ["Cocktails", "Finger Food", "Asian"],
        "tags": ["EatMap Nightlife", "Rank #7", "cocktail bar", "hotel bar", "Collection: Drinks & Nightlife", "Cost: Rs 2,500 for two", "Hours: Evening to late night", "Distance: 13.4 km"],
        "occasions": ["date", "pub-night", "after-work"],
        "emoji": "🍸",
        "latitude": 17.4328,
        "longitude": 78.3399,
        "map_x": 84,
        "map_y": 53,
        "rating": 4.8,
        "reviews_count": 4300,
        "score": 9.0,
        "food_score": 4.4,
        "ambience_score": 4.8,
        "service_score": 4.7,
        "value_score": 3.9,
        "wait_score": 4.0,
        "ai_summary": "A hotel cocktail bar for quieter conversations, precise drinks, and a more composed Gachibowli night out.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-7",
    },
    {
        "name": "Rasa By Ashoka",
        "area": "Banjara Hills",
        "category": "pub",
        "restaurant_type": "casual dining bar",
        "cuisines": ["North Indian", "Continental", "Chinese"],
        "tags": ["EatMap Nightlife", "Rank #8", "casual drinks", "group friendly", "Collection: Drinks & Nightlife", "Cost: Rs 2,000 for two", "Hours: Lunch to late night", "Distance: 4.7 km"],
        "occasions": ["party", "team-lunch", "pub-night"],
        "emoji": "🍽",
        "latitude": 17.4138,
        "longitude": 78.4391,
        "map_x": 39,
        "map_y": 47,
        "rating": 4.8,
        "reviews_count": 5600,
        "score": 8.9,
        "food_score": 4.6,
        "ambience_score": 4.5,
        "service_score": 4.4,
        "value_score": 4.2,
        "wait_score": 3.8,
        "ai_summary": "A dependable Banjara Hills option for mixed-cuisine dinner, drinks, and groups that need something easy to agree on.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-8",
    },
    {
        "name": "Daily Rituals",
        "area": "Hitech City",
        "category": "pub",
        "restaurant_type": "pub",
        "cuisines": ["Bar Food", "Continental", "Asian"],
        "tags": ["EatMap Nightlife", "Rank #9", "bar food", "casual", "Collection: Drinks & Nightlife", "Cost: Rs 2,000 for two", "Hours: Lunch to late night", "Distance: 10.8 km"],
        "occasions": ["after-work", "pub-night", "party"],
        "emoji": "🍺",
        "latitude": 17.4481,
        "longitude": 78.3796,
        "map_x": 66,
        "map_y": 59,
        "rating": 4.8,
        "reviews_count": 3900,
        "score": 8.8,
        "food_score": 4.4,
        "ambience_score": 4.5,
        "service_score": 4.3,
        "value_score": 4.3,
        "wait_score": 4.0,
        "ai_summary": "A casual Hitech City drinks pick for repeatable after-work plans, bar food, and easy group energy.",
        "external_provider": "zomato",
        "external_id": "zomato-nightlife-hyd-9",
    },
]


def clamp(value: float, minimum: float, maximum: float) -> float:
    return max(minimum, min(maximum, value))


def build_generated_places() -> list[dict]:
    places = [dict(place) for place in FEATURED_PLACES + CURATED_RESTAURANT_PLACES + CURATED_NIGHTLIFE_PLACES]
    areas = list(AREA_COORDS.items())
    categories = list(CATEGORY_PROFILES.items())
    target_total = 108

    i = 0
    while len(places) < target_total:
        category, profile = categories[i % len(categories)]
        area, (lat, lng, map_x, map_y) = areas[(i * 3 + i // len(categories)) % len(areas)]
        name_root = profile["names"][(i // len(categories)) % len(profile["names"])]
        branch_suffix = "" if not any(p["name"] == name_root and p["area"] == area for p in places) else f" {area}"
        rating = round(4.05 + ((i * 7) % 10) * 0.08, 1)
        score = round(clamp(7.4 + ((i * 11) % 18) * 0.12, 7.2, 9.5), 1)
        x_offset = ((i % 5) - 2) * 1.4
        y_offset = (((i // 5) % 5) - 2) * 1.2
        coord_offset = ((i % 7) - 3) * 0.0021

        places.append(
            {
                "name": f"{name_root}{branch_suffix}",
                "area": area,
                "category": category,
                "restaurant_type": profile["restaurant_type"],
                "cuisines": list(profile["cuisines"]),
                "tags": list(dict.fromkeys([*profile["tags"], area, "Open now" if i % 4 else "Trending"])),
                "occasions": list(profile["occasions"]),
                "emoji": profile["emoji"],
                "latitude": round(lat + coord_offset, 6),
                "longitude": round(lng - coord_offset, 6),
                "map_x": round(clamp(map_x + x_offset, 5, 95), 2),
                "map_y": round(clamp(map_y + y_offset, 6, 88), 2),
                "rating": rating,
                "reviews_count": 450 + ((i * 173) % 8200),
                "score": score,
                "food_score": round(clamp(rating + 0.1 - (i % 3) * 0.08, 3.6, 5.0), 1),
                "ambience_score": round(clamp(3.5 + ((i * 5) % 15) * 0.1, 3.2, 4.9), 1),
                "service_score": round(clamp(3.6 + ((i * 4) % 13) * 0.1, 3.3, 4.8), 1),
                "value_score": round(clamp(3.7 + ((i * 6) % 14) * 0.1, 3.4, 5.0), 1),
                "wait_score": round(clamp(2.8 + ((i * 8) % 17) * 0.1, 2.7, 4.7), 1),
                "ai_summary": (
                    f"{name_root} in {area} is a strong {category.replace('-', ' ')} pick for "
                    f"{', '.join(profile['occasions'][:2]).replace('-', ' ')}. "
                    "Use the filters and heatmap to compare it with nearby options."
                ),
            }
        )
        i += 1

    return places


SEED_PLACES = build_generated_places()


async def seed_database(session: AsyncSession) -> None:
    existing_count = await session.scalar(select(func.count(Place.id)))
    existing_names = set((await session.scalars(select(Place.name))).all())
    missing_places = [place for place in SEED_PLACES if place["name"] not in existing_names]

    if not missing_places and existing_count >= 100:
        return

    session.add_all(Place(**place) for place in missing_places)
    await session.commit()
